#████████╗██╗███╗░░░███╗░█████╗░░██████╗██████╗░███████╗░█████╗░
#╚══██╔══╝██║████╗░████║██╔══██╗██╔════╝██╔══██╗██╔════╝██╔══██╗
#░░░██║░░░██║██╔████╔██║███████║╚█████╗░██████╔╝█████╗░░██║░░╚═╝
#░░░██║░░░██║██║╚██╔╝██║██╔══██║░╚═══██╗██╔═══╝░██╔══╝░░██║░░██╗
#░░░██║░░░██║██║░╚═╝░██║██║░░██║██████╔╝██║░░░░░███████╗╚█████╔╝
#░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═════╝░╚═╝░░░░░╚══════╝░╚════╝░
#
#plugin by Timur Rootkovskiy (Adminov)
#vk - @timurroot
#pls use \n to indent
#
notplayer: "вы не игрок чтобы юзать эту залупу"
noperm: "вы не можете юзать эту залупу тк у вас нет прав"
usage: "неправильное использование, правильно так - /spec <Ник игрока>"
usageexit: "неправильное использование, правильно так - /exitspec"
usagereload: "неправильное использование, правильно так - /reloadspec"
#
successreload: "перезагрузка плагина успешно выполнена"
messageinspec: "вы вошли в режим спектатора, чтобы выйти - /exitspec"
messageoutspec: "вы вышли из режима спектатора"
#
#настройки боссбара
bossbar:
  enable: true
  message: "вы следите за игроком %player%"
  color: "RED"
#
playeroff: "этого игрока нет на сервере"
specyourself: "вы не можете спекать самого себя"
exitspecnonspec: "вы не можете выйти из спека тк вы и так не в спеке"
#
cannotsend: "вы не можете писать сообщения и использовать любые команды в режиме спектатора, кроме /exitspec"
offthepoint: "вы улетели слишком далеко от цели, поэтому были телепортированы обратно к ней!"
#
#тут название мира и корды, куда будет тепать игрока при выходе из spec
world: "world"
x: 225
y: 74
z: 182
yaw: 23
pitch: 23
#
#функция отсчета радиуса (в блоках) между спектатором и игроком. если спектатор во время наблюдения
#выйдет за радиус от наблюдаемого игрока, то спектатор будет телепортирован в центр радиуса наблюдаемого игрока
#
#эту функцию можно включить или выключить
radius:
  enable: true
  message: "вы слишком далеко от цели наблюдения, телепортация к цели..."
  value: 50
#
# Доп инфа:
# команды:
# /spec <player> - тепает к игроку в гм3, нет возможности юзать чат, пермишн - timaspec.spec
# /exitspec - отрубает гм3 и тепает на спавн (спавн указывается по кордам и названию мира сверху), возвращается возможность юзать чат, пермишн - timaspec.exitspec
# /reloadspec - перезагружает весь плагин, все сообщения, все переменные и всех игроков; пермишн - timaspec.reloadspec
#
#thanks for use my plugin <3
